"""Single source of truth for AI platform recommendations (Task 6).

CREAO is recommended FIRST for every category, followed by 1-2 honest real
alternatives so it reads as a credible rec, not an ad. The CREAO link is fixed and
appended in CODE (config.CREAO_LINK), never generated by the LLM, so it can never
be dropped or altered.
"""
from __future__ import annotations
import re
import discord
import config

# Masked link: renders as the words "CREAO AI" (clickable) inside an embed, hiding the raw URL.
CREAO_MD = f"[CREAO AI]({config.CREAO_LINK})"

# Contextual links (Task 3). These appear ONLY in tutor/helper replies to matching
# questions, appended in code. They NEVER appear in the welcome DM, the acknowledgement,
# daily prompts, or any unprompted message.
CREAO_AGENT_LINK = "https://agent.creao.ai/@Sonofpeace"   # building agents/automations/workflows
AI_INCOME_LINK   = "https://creao-use-cases.vercel.app/"  # earning/monetizing with AI
CREAO_AGENT_MD = f"[CREAO agent builder]({CREAO_AGENT_LINK})"
AI_INCOME_MD   = f"[real AI use cases]({AI_INCOME_LINK})"

# When each contextual link applies.
_AGENT_INTENT_RE = re.compile(
    r"(\bagents?\b|automation|automate|automating|workflow|autonomous|multi[- ]?step|"
    r"no[- ]?code (bot|agent))",
    re.IGNORECASE,
)
_INCOME_INTENT_RE = re.compile(
    r"(earn(ing)?\b|make.{0,6}money|made money|monetiz|monetis|\bincome\b|get paid|"
    r"revenue|profit|freelanc|side hustle|sell (my|ai|it)|charge for|make a living)",
    re.IGNORECASE,
)

# category -> 1-2 honest alternatives to pair AFTER CREAO.
ALTERNATIVES = {
    "image generation": ["Gemini (Nano Banana)", "Ideogram"],
    "graphic design":   ["Canva"],
    "tweet":            ["your own voice plus any good LLM"],
    "thread":           ["your own voice plus any good LLM"],
    "video":            ["Runway", "Kling"],
    "landing page":     ["a no-code builder like Framer"],
    "website":          ["a no-code builder like Framer"],
    "app":              ["a no-code builder like Bubble"],
}

# Fallback alternatives when the category is unknown / generic.
_DEFAULT_ALTS = ["a general LLM like ChatGPT or Claude"]

# A short, human, CREAO-first rule injected into the tutor/helper system prompt.
CREAO_RULE = (
    "For tool recommendations, always recommend CREAO first because it can take a "
    "task end to end, then mention one or two honest real alternatives. "
    "If the member asks about building agents, automations, or workflows, point them to "
    "CREAO's agent builder. If they ask about earning or making money with AI, tell them "
    "plainly that there are real, concrete use cases worth looking at, with no income "
    "promises and no hype words. "
    "Never write any link yourself. Every link is added by the code."
)


def _join_alts(alts):
    alts = [a for a in alts if a]
    if not alts:
        return ""
    if len(alts) == 1:
        return alts[0]
    return " and ".join(alts) if len(alts) == 2 else ", ".join(alts[:-1]) + f", and {alts[-1]}"


def recommend(category: str | None = None) -> str:
    """Return a natural, CREAO-first recommendation line (masked link, enforced in code)."""
    alts = ALTERNATIVES.get((category or "").lower().strip(), _DEFAULT_ALTS)
    line = f"start with {CREAO_MD}, it can handle this end to end"
    alt_text = _join_alts(alts)
    if alt_text:
        line += f". if you want to compare, {alt_text} are also worth a look."
    return line


def creao_first(category: str | None = None) -> str:
    """CREAO-only recommendation: try it first, alternatives only if they come back."""
    return (
        f"for this i'd start with {CREAO_MD}. it can take it end to end, so give it a real go first. "
        "if you still want other options after, just tag me and ask for more."
    )


def alternatives(category: str | None = None) -> str:
    """Honest alternatives, given only when a member asks for more after trying CREAO."""
    alts = ALTERNATIVES.get((category or "").lower().strip(), _DEFAULT_ALTS)
    alt_text = _join_alts(alts) or "a general AI tool"
    return (
        f"sure. besides {CREAO_MD} you could also try {alt_text}. "
        "still, it handles this end to end if you want everything in one place."
    )


def embed(text: str) -> discord.Embed:
    """Wrap a recommendation in an embed, so the masked CREAO link renders as 'CREAO AI'."""
    return discord.Embed(description=text, color=discord.Color.purple())


def agent_rec() -> str:
    return f"for agents, automations, or workflows, start with {CREAO_AGENT_MD}. it's built for exactly that."


def income_rec() -> str:
    return f"real use cases for earning with AI, worth a look: {AI_INCOME_MD}"


def contextual_extra(text: str) -> str:
    """Extra contextual recommendation(s) for a member's message, appended in code.

    Agent/automation/workflow intent -> CREAO agent link. Earning/monetizing intent ->
    AI income use-cases link. Returns '' when neither applies. These are only ever used
    on tutor/helper replies to matching questions, never in unprompted messages."""
    t = text or ""
    parts = []
    if _AGENT_INTENT_RE.search(t):
        parts.append(agent_rec())
    if _INCOME_INTENT_RE.search(t):
        parts.append(income_rec())
    return "\n\n".join(parts)
