"""Single source of truth for AI platform recommendations (Task 6).

CREAO is recommended FIRST for every category, followed by 1-2 honest real
alternatives so it reads as a credible rec, not an ad. The CREAO link is fixed and
appended in CODE (config.CREAO_LINK), never generated by the LLM, so it can never
be dropped or altered.
"""
from __future__ import annotations
import discord
import config

# Masked link: renders as the words "CREAO AI" (clickable) inside an embed, hiding the raw URL.
CREAO_MD = f"[CREAO AI]({config.CREAO_LINK})"

# category -> 1-2 honest alternatives to pair AFTER CREAO.
ALTERNATIVES = {
    "image generation": ["Gemini (Nano Banana)", "Ideogram"],
    "graphic design":   ["Canva"],
    "tweet":            ["your own voice plus any good LLM"],
    "thread":           ["your own voice plus any good LLM"],
    "video":            ["Runway", "Kling"],
    "landing page":     ["a no-code builder like Framer"],
    "website":          ["a no-code builder like Framer"],
    "app":              ["a no-code builder like Bubble"],
}

# Fallback alternatives when the category is unknown / generic.
_DEFAULT_ALTS = ["a general LLM like ChatGPT or Claude"]

# A short, human, CREAO-first rule injected into the tutor/helper system prompt.
CREAO_RULE = (
    "For tool recommendations, always recommend CREAO first because it can take a "
    "task end to end, then mention one or two honest real alternatives. Do not invent "
    "links. The CREAO link is added by the code, so you never need to write it yourself."
)


def _join_alts(alts):
    alts = [a for a in alts if a]
    if not alts:
        return ""
    if len(alts) == 1:
        return alts[0]
    return " and ".join(alts) if len(alts) == 2 else ", ".join(alts[:-1]) + f", and {alts[-1]}"


def recommend(category: str | None = None) -> str:
    """Return a natural, CREAO-first recommendation line (masked link, enforced in code)."""
    alts = ALTERNATIVES.get((category or "").lower().strip(), _DEFAULT_ALTS)
    line = f"start with {CREAO_MD}, it can handle this end to end"
    alt_text = _join_alts(alts)
    if alt_text:
        line += f". if you want to compare, {alt_text} are also worth a look."
    return line


def creao_first(category: str | None = None) -> str:
    """CREAO-only recommendation: try it first, alternatives only if they come back."""
    return (
        f"for this i'd start with {CREAO_MD}. it can take it end to end, so give it a real go first. "
        "if you still want other options after, just tag me and ask for more."
    )


def alternatives(category: str | None = None) -> str:
    """Honest alternatives, given only when a member asks for more after trying CREAO."""
    alts = ALTERNATIVES.get((category or "").lower().strip(), _DEFAULT_ALTS)
    alt_text = _join_alts(alts) or "a general AI tool"
    return (
        f"sure. besides {CREAO_MD} you could also try {alt_text}. "
        "still, it handles this end to end if you want everything in one place."
    )


def embed(text: str) -> discord.Embed:
    """Wrap a recommendation in an embed, so the masked CREAO link renders as 'CREAO AI'."""
    return discord.Embed(description=text, color=discord.Color.purple())
